/**
 * GS Softwares Settings Declarations Schema
 * Master Schema Contract v1.0 (Decisive)
 * Single source of truth for all configurable properties across the entire 109+ tool ecosystem.
 */

import { SettingCategory, SettingDefinition, SuiteDefaultGroup } from './types';

export const SETTING_CATEGORIES: Array<{
  id: SettingCategory;
  label: string;
  icon: string;
  badge?: string;
  description: string;
}> = [
  { id: 'performance', label: 'Performance Mode', icon: 'Cpu', badge: 'Primary', description: 'Adjust speed, battery saving, and hardware acceleration to match your device' },
  { id: 'appearance', label: 'Appearance', icon: 'Palette', description: 'Themes, accent colors, button depth, font size, and contrast' },
  { id: 'general', label: 'General', icon: 'Globe', description: 'Language, startup page, default save location, and auto-save timer' },
  { id: 'privacy', label: 'Privacy & Security', icon: 'Shield', description: 'Data protection guarantees, history cleanup, and security settings' },
  { id: 'files', label: 'File Defaults', icon: 'Folder', description: 'Default export formats, quality levels, and file notifications' },
  { id: 'advanced', label: 'Advanced', icon: 'Zap', description: 'Speed overrides, memory limits, and experimental features' },
  { id: 'tools', label: 'Tool Defaults', icon: 'Wrench', description: 'Default settings for each individual studio tool' },
  { id: 'shortcuts', label: 'Shortcuts', icon: 'Keyboard', description: 'Keyboard shortcut map for fast navigation' },
  { id: 'data', label: 'Data & Storage', icon: 'Database', description: 'Manage saved files, backups, and device storage usage' },
  { id: 'about', label: 'About', icon: 'Info', description: 'App version, offline status, and privacy details' },
];

export const SETTINGS_SCHEMA: SettingDefinition[] = [
  // ─────────────────────────────────────────────────────────────
  // 1. PERFORMANCE MODE
  // ─────────────────────────────────────────────────────────────
  {
    key: 'perf.tier',
    category: 'performance',
    label: 'Performance Mode',
    description: 'Balances processing speed, battery consumption, and visual quality for your device.',
    type: 'tier-selector',
    default: 'balanced',
    tierAware: true,
    autoDetect: true,
    options: [
      { value: 'eco', label: 'Eco', desc: 'Fast and battery-friendly. Great for older phones and laptops on battery.' },
      { value: 'balanced', label: 'Balanced', desc: 'Recommended. Smooth performance and high quality for most devices.' },
      { value: 'performance', label: 'High Performance', desc: 'Maximum quality and power for high-end computers and workstations.' },
    ],
  },
  {
    key: 'perf.autoDetect',
    category: 'performance',
    label: 'Auto-detect device capability',
    description: 'Automatically chooses the best speed and battery settings for your device.',
    type: 'boolean',
    default: true,
    warning: 'Disabling auto-detection allows you to customize threads, memory, and graphics manually in Advanced Settings.',
  },

  // ─────────────────────────────────────────────────────────────
  // 2. APPEARANCE
  // ─────────────────────────────────────────────────────────────
  {
    key: 'appearance.theme',
    category: 'appearance',
    label: 'Theme',
    description: 'Switch between light, dark, and system color schemes.',
    type: 'enum',
    default: 'system',
    options: [
      { value: 'light', label: 'Light Mode', desc: 'Clean, bright background with clear text' },
      { value: 'dark', label: 'Dark Mode', desc: 'Deep dark background with soft neon accents' },
      { value: 'system', label: 'Match System', desc: 'Automatically matches your device settings' },
    ],
  },
  {
    key: 'appearance.accent',
    category: 'appearance',
    label: 'Accent Color',
    description: 'Choose your preferred highlight color for buttons and active tools.',
    type: 'color',
    default: '#0066FF',
    options: [
      { value: '#0066FF', label: 'Electric Blue (Default)' },
      { value: '#0891b2', label: 'Cyan Teal' },
      { value: '#8b5cf6', label: 'Electric Purple' },
      { value: '#10b981', label: 'Emerald Mint' },
      { value: '#f59e0b', label: 'Amber Gold' },
      { value: '#f43f5e', label: 'Neon Rose' },
    ],
  },
  {
    key: 'appearance.depth',
    category: 'appearance',
    label: 'Button & Card Depth',
    description: 'Adjust the softness and 3D depth of buttons and cards (0–100%).',
    type: 'number',
    default: 50,
    min: 0,
    max: 100,
    step: 5,
    unit: '%',
  },
  {
    key: 'appearance.textSize',
    category: 'appearance',
    label: 'Text Size',
    description: 'Quickly adjust interface text sizing for small screens and mobile viewports.',
    type: 'enum',
    default: 'medium',
    options: [
      { value: 'small', label: 'Small', desc: 'Compact typography for dense mobile screens' },
      { value: 'medium', label: 'Medium', desc: 'Balanced standard readable size' },
      { value: 'large', label: 'Large', desc: 'High readability for larger text preference' },
    ],
  },
  {
    key: 'appearance.fontSize',
    category: 'appearance',
    label: 'Base Font Size',
    description: 'Fine-tune exact pixel base size across all tools (12–24 px).',
    type: 'number',
    default: 16,
    min: 12,
    max: 24,
    step: 1,
    unit: 'px',
  },
  {
    key: 'appearance.compact',
    category: 'appearance',
    label: 'Compact Mode',
    description: 'Use smaller toolbars and compact menus to give you more workspace area.',
    type: 'boolean',
    default: false,
  },
  {
    key: 'appearance.highContrast',
    category: 'appearance',
    label: 'High Contrast',
    description: 'Make text, outlines, and buttons sharper and easier to see.',
    type: 'boolean',
    default: false,
  },

  // ─────────────────────────────────────────────────────────────
  // 3. GENERAL
  // ─────────────────────────────────────────────────────────────
  {
    key: 'general.language',
    category: 'general',
    label: 'Language',
    description: 'Interface display language (i18n ready).',
    type: 'enum',
    default: 'en',
    options: [
      { value: 'en', label: 'English' },
      { value: 'es', label: 'Español' },
      { value: 'fr', label: 'Français' },
      { value: 'de', label: 'Deutsch' },
      { value: 'ja', label: '日本語' },
      { value: 'zh', label: '中文' },
      { value: 'ar', label: 'العربية' },
      { value: 'hi', label: 'हिन्दी' },
    ],
  },
  {
    key: 'general.startupPage',
    category: 'general',
    label: 'Startup Page',
    description: 'Choose which view opens when you start the app.',
    type: 'enum',
    default: 'home',
    options: [
      { value: 'home', label: 'Home Hub' },
      { value: 'lastTool', label: 'Resume Last Active Tool' },
      { value: 'allTools', label: 'All Tools Catalog' },
      { value: 'pixels', label: 'Photo Studio' },
      { value: 'canvas', label: 'Drawing Canvas' },
      { value: 'pdf', label: 'PDF Studio' },
      { value: 'video', label: 'Video Studio' },
      { value: 'audio', label: 'Audio Studio' },
      { value: 'text', label: 'Text Editor' },
    ],
  },
  {
    key: 'general.saveDestination',
    category: 'general',
    label: 'Default Save Location',
    description: 'How downloaded files are saved to your device.',
    type: 'enum',
    default: 'download',
    options: [
      { value: 'download', label: 'Direct Download' },
      { value: 'fsAccess', label: 'Ask Where to Save Each Time' },
      { value: 'opfs', label: 'Internal App Storage' },
    ],
  },
  {
    key: 'general.fileNaming',
    category: 'general',
    label: 'File Naming Pattern',
    description: 'Template used when naming downloaded files ({tool}_{date}_{n}).',
    type: 'string',
    default: '{tool}_{date}_{n}',
    placeholder: 'e.g. {tool}_{date}_{n}',
  },
  {
    key: 'general.autosaveSec',
    category: 'general',
    label: 'Auto-save Interval',
    description: 'How often drawings and text drafts are automatically saved to your browser (5–300 s).',
    type: 'number',
    default: 10,
    min: 5,
    max: 300,
    step: 5,
    unit: 's',
  },
  {
    key: 'general.systemNotifications',
    category: 'general',
    label: 'System Task Notifications',
    description: 'Local device alerts when background exports or conversions complete. Never sent over the internet.',
    type: 'enum',
    default: 'background',
    options: [
      { value: 'off', label: 'Disabled' },
      { value: 'background', label: 'Only When Tab is Hidden (Recommended)' },
      { value: 'always', label: 'Always Notify' },
    ],
  },
  {
    key: 'general.haptics',
    category: 'general',
    label: 'Device Haptic Feedback',
    description: 'Vibration pulses on completion, warning, or error (mobile and supported trackpads).',
    type: 'boolean',
    default: true,
  },
  {
    key: 'general.showFileNames',
    category: 'general',
    label: 'Show Filenames in Notifications',
    description: 'If disabled, notification banners use generic privacy titles with zero file names.',
    type: 'boolean',
    default: false,
  },
  {
    key: 'general.batchSummaryThreshold',
    category: 'general',
    label: 'Batch Summary Notification Threshold',
    description: 'Number of concurrent items that triggers a single bundled summary notification instead of individual cards.',
    type: 'number',
    default: 4,
    min: 2,
    max: 20,
    step: 1,
  },

  // ─────────────────────────────────────────────────────────────
  // 4. PRIVACY & SECURITY
  // ─────────────────────────────────────────────────────────────
  {
    key: 'privacy.noTelemetry',
    category: 'privacy',
    label: 'Zero Tracking Guarantee',
    description: 'GS Softwares collects zero analytics, tracking cookies, or personal data. 100% private.',
    type: 'readonly',
    default: true,
    badge: '100% Private',
  },
  {
    key: 'privacy.proofLink',
    category: 'privacy',
    label: 'Privacy Details',
    description: 'Learn how all file processing happens directly on your device.',
    type: 'readonly',
    default: 'https://github.com/Gulshan-Singh-gs/gs-softwares#privacy-architecture',
    url: 'https://github.com/Gulshan-Singh-gs/gs-softwares#privacy-architecture',
    badge: 'View Open Source Proof',
  },
  {
    key: 'privacy.historyRetention',
    category: 'privacy',
    label: 'Keep Project History',
    description: 'Automatically clean up older saved files from your browser storage.',
    type: 'enum',
    default: 30,
    options: [
      { value: 7, label: '7 Days' },
      { value: 14, label: '14 Days' },
      { value: 30, label: '30 Days (Default)' },
      { value: 90, label: '90 Days' },
    ],
  },
  {
    key: 'privacy.clipboardClearSec',
    category: 'privacy',
    label: 'Clear Copied Items',
    description: 'Automatically clear copied text and sensitive passwords from your clipboard.',
    type: 'enum',
    default: 30,
    options: [
      { value: 0, label: 'Never Clear' },
      { value: 10, label: '10 Seconds' },
      { value: 30, label: '30 Seconds' },
      { value: 60, label: '60 Seconds' },
    ],
  },
  {
    key: 'privacy.vaultPassword',
    category: 'privacy',
    label: 'Master Password',
    description: 'Set an optional password to protect sensitive files stored on this device.',
    type: 'secret',
    default: '',
    placeholder: 'Set or change master password',
  },

  // ─────────────────────────────────────────────────────────────
  // 5. FILE HANDLING
  // ─────────────────────────────────────────────────────────────
  {
    key: 'files.image.format',
    category: 'files',
    label: 'Default Image Format',
    description: 'Standard format used when saving exported images.',
    type: 'enum',
    default: 'webp',
    options: [
      { value: 'webp', label: 'WebP (Small file size & high quality)' },
      { value: 'jpg', label: 'JPG (Universal compatibility)' },
      { value: 'png', label: 'PNG (Transparent backgrounds)' },
      { value: 'avif', label: 'AVIF (Next-generation compact)' },
    ],
  },
  {
    key: 'files.image.quality',
    category: 'files',
    label: 'Default Image Quality',
    description: 'Standard image quality level for exports (1–100%).',
    type: 'number',
    default: 80,
    min: 1,
    max: 100,
    step: 1,
    unit: '%',
  },
  {
    key: 'files.audio.format',
    category: 'files',
    label: 'Default Audio Format',
    description: 'Standard format used when saving exported audio.',
    type: 'enum',
    default: 'opus',
    options: [
      { value: 'opus', label: 'Opus (Modern compact audio)' },
      { value: 'mp3', label: 'MP3 (Standard universal format)' },
      { value: 'wav', label: 'WAV (Uncompressed studio sound)' },
      { value: 'flac', label: 'FLAC (Lossless compression)' },
    ],
  },
  {
    key: 'files.preserveMetadata',
    category: 'files',
    label: 'Keep Camera & Location Info',
    description: 'Preserve camera details, dates, and audio tags on exported files.',
    type: 'boolean',
    default: false,
  },
  {
    key: 'files.overwriteBehavior',
    category: 'files',
    label: 'Duplicate File Action',
    description: 'What to do when saving a file with the same name as an existing one.',
    type: 'enum',
    default: 'rename',
    options: [
      { value: 'rename', label: 'Auto-Rename (Add number suffix)' },
      { value: 'overwrite', label: 'Overwrite Existing File' },
      { value: 'ask', label: 'Ask Me Each Time' },
    ],
  },
  {
    key: 'files.largeFileWarnMB',
    category: 'files',
    label: 'Large File Reminder (MB)',
    description: 'Show a notice when opening files larger than this size (10–1000 MB).',
    type: 'number',
    default: 100,
    min: 10,
    max: 1000,
    step: 25,
    unit: 'MB',
  },

  // ─────────────────────────────────────────────────────────────
  // 6. ADVANCED
  // ─────────────────────────────────────────────────────────────
  {
    key: 'perf.workerCountOverride',
    category: 'advanced',
    label: 'Processing Tasks',
    description: 'Number of parallel tasks to run at once (available when auto-detect is turned off).',
    type: 'number',
    default: 4,
    min: 1,
    max: 16,
    step: 1,
    dependsOn: '!perf.autoDetect',
  },
  {
    key: 'perf.gpuOverride',
    category: 'advanced',
    label: 'Graphics Acceleration',
    description: 'Choose how your device graphics card speeds up photo and video filters.',
    type: 'enum',
    default: 'webgl',
    dependsOn: '!perf.autoDetect',
    options: [
      { value: 'disabled', label: 'Disabled (Standard CPU)' },
      { value: 'webgl', label: 'WebGL 2 Acceleration (Fast)' },
      { value: 'webgpu', label: 'WebGPU (Ultra High Speed)' },
    ],
  },
  {
    key: 'perf.memoryOverrideMB',
    category: 'advanced',
    label: 'Memory Limit (MB)',
    description: 'Maximum temporary memory allocated for processing large files.',
    type: 'enum',
    default: 512,
    dependsOn: '!perf.autoDetect',
    options: [
      { value: 128, label: '128 MB' },
      { value: 256, label: '256 MB' },
      { value: 512, label: '512 MB' },
      { value: 1024, label: '1024 MB (1 GB)' },
      { value: 2048, label: '2048 MB (2 GB)' },
    ],
  },
  {
    key: 'perf.cacheSizeMB',
    category: 'advanced',
    label: 'Temporary Cache Limit (MB)',
    description: 'Maximum temporary storage used to speed up edits (64–1024 MB).',
    type: 'enum',
    default: 256,
    options: [
      { value: 64, label: '64 MB' },
      { value: 128, label: '128 MB' },
      { value: 256, label: '256 MB (Recommended)' },
      { value: 512, label: '512 MB' },
      { value: 1024, label: '1024 MB' },
    ],
  },
  {
    key: 'advanced.prefetchModels',
    category: 'advanced',
    label: 'Smart Tool Preloading',
    description: 'When to prepare intelligent features like background removal and noise reduction.',
    type: 'enum',
    default: 'onToolOpen',
    options: [
      { value: 'onToolOpen', label: 'When Tool Opens (Balanced)' },
      { value: 'onAppLoad', label: 'When App Starts (Fastest)' },
      { value: 'never', label: 'Only When Used' },
    ],
  },
  {
    key: 'advanced.developerMode',
    category: 'advanced',
    label: 'Developer Mode',
    description: 'Show technical statistics and detailed memory monitors in the console.',
    type: 'boolean',
    default: false,
  },
  {
    key: 'advanced.experimentalFeatures',
    category: 'advanced',
    label: 'Experimental Features',
    description: 'Try out early preview tools and upcoming experimental features.',
    type: 'boolean',
    default: false,
  },
  {
    key: 'perf.clearCache',
    category: 'advanced',
    label: 'Clear Temporary Cache',
    description: 'Delete temporary scratch files to free up browser storage.',
    type: 'action',
    default: null,
    actionId: 'clearCache',
  },

  // ─────────────────────────────────────────────────────────────
  // 7. TOOL DEFAULTS
  // ─────────────────────────────────────────────────────────────
  {
    key: 'tools.suiteDefaults',
    category: 'tools',
    label: 'Individual Tool Defaults',
    description: 'Customize default settings for specific studio tools.',
    type: 'suite-defaults',
    default: {},
  },

  // ─────────────────────────────────────────────────────────────
  // 8. SHORTCUTS
  // ─────────────────────────────────────────────────────────────
  {
    key: 'shortcuts.bindings',
    category: 'shortcuts',
    label: 'Shortcut Map',
    description: 'Overview of all keyboard shortcut key combinations.',
    type: 'computed',
    default: {},
    computedId: 'diagnostics',
  },
  {
    key: 'shortcuts.reset',
    category: 'shortcuts',
    label: 'Reset Shortcuts',
    description: 'Restore all keyboard shortcuts to their default combinations.',
    type: 'action',
    default: null,
    actionId: 'resetDefaults',
  },

  // ─────────────────────────────────────────────────────────────
  // 9. DATA & STORAGE
  // ─────────────────────────────────────────────────────────────
  {
    key: 'data.usage',
    category: 'data',
    label: 'Storage Usage',
    description: 'Shows how much storage is currently used on your device.',
    type: 'computed',
    default: null,
    computedId: 'storageUsage',
  },
  {
    key: 'data.export',
    category: 'data',
    label: 'Backup Settings',
    description: 'Download a backup file of your custom settings.',
    type: 'action',
    default: null,
    actionId: 'export',
  },
  {
    key: 'data.import',
    category: 'data',
    label: 'Restore Settings',
    description: 'Restore your settings from a previously saved backup file.',
    type: 'action',
    default: null,
    actionId: 'import',
  },
  {
    key: 'data.clearHistory',
    category: 'data',
    label: 'Clear Recent History',
    description: 'Remove recent workspace file history while keeping your custom settings.',
    type: 'action',
    default: null,
    actionId: 'clearHistory',
    warning: 'This will remove recent files from your history while keeping your settings intact.',
  },
  {
    key: 'data.clearAll',
    category: 'data',
    label: 'Reset Everything',
    description: 'Erase all stored files, workspace history, and custom settings on this device.',
    type: 'action',
    default: null,
    actionId: 'clearAll',
    warning: 'Warning: This will permanently delete all stored workspace files and restore all settings to default.',
  },

  // ─────────────────────────────────────────────────────────────
  // 10. ABOUT
  // ─────────────────────────────────────────────────────────────
  {
    key: 'about.diagnostics',
    category: 'about',
    label: 'Device Details & Privacy Status',
    description: 'View current device specifications and offline availability.',
    type: 'computed',
    default: null,
    computedId: 'diagnostics',
  },
];

// 12 Suite Default Groups for Tool Defaults Accordion
export const SUITE_DEFAULT_GROUPS: SuiteDefaultGroup[] = [
  {
    suiteId: 'image',
    suiteName: 'Photo Studio',
    icon: 'Image',
    settings: [
      {
        key: 'tools.image.format',
        category: 'tools',
        label: 'Default Output Format',
        description: 'Standard format used when saving photos',
        type: 'enum',
        default: 'webp',
        inheritsKey: 'files.image.format',
        options: [
          { value: 'webp', label: 'WebP' },
          { value: 'jpg', label: 'JPG' },
          { value: 'png', label: 'PNG' },
          { value: 'avif', label: 'AVIF' },
        ],
      },
      {
        key: 'tools.image.quality',
        category: 'tools',
        label: 'Default Quality',
        description: 'Compression quality level (1–100%)',
        type: 'number',
        default: 80,
        min: 1,
        max: 100,
        unit: '%',
        inheritsKey: 'files.image.quality',
      },
      {
        key: 'tools.image.editorMode',
        category: 'tools',
        label: 'Studio Layout',
        description: 'Choose your default workspace view.',
        type: 'enum',
        default: 'simple',
        options: [
          { value: 'simple', label: 'Simple (Quick adjustments)' },
          { value: 'advanced', label: 'Full Studio (All controls)' },
        ],
      },
      {
        key: 'tools.image.bgRemoverModel',
        category: 'tools',
        label: 'Background Remover Quality',
        description: 'Quality level for automatic background removal',
        type: 'enum',
        default: 'auto',
        inheritsKey: 'perf.aiModels',
        options: [
          { value: 'auto', label: 'Auto (Recommended)' },
          { value: 'lightweight', label: 'Fast' },
          { value: 'full', label: 'High Precision' },
        ],
      },
    ],
  },
  {
    suiteId: 'vector',
    suiteName: 'Drawing Canvas',
    icon: 'PenTool',
    settings: [
      {
        key: 'tools.vector.renderer',
        category: 'tools',
        label: 'Drawing Smoothness Engine',
        description: 'Graphics backend used for smooth strokes.',
        type: 'enum',
        default: 'auto',
        options: [
          { value: 'auto', label: 'Auto (Recommended)' },
          { value: 'webgl', label: 'Hardware Accelerated' },
          { value: 'canvas2d', label: 'Standard Canvas' },
        ],
      },
      {
        key: 'tools.vector.antiAliasing',
        category: 'tools',
        label: 'Smooth Line Outlines',
        description: 'Keep lines crisp and smooth at high zoom.',
        type: 'boolean',
        default: true,
      },
      {
        key: 'tools.vector.highDpi',
        category: 'tools',
        label: 'High-Resolution Display Support',
        description: 'Render at the sharpest quality for your screen.',
        type: 'boolean',
        default: true,
      },
    ],
  },
  {
    suiteId: 'pdf',
    suiteName: 'PDF Studio',
    icon: 'FileText',
    settings: [
      {
        key: 'tools.pdf.dpi',
        category: 'tools',
        label: 'Page Render Sharpness (DPI)',
        description: 'Resolution when viewing and converting PDF pages.',
        type: 'number',
        default: 150,
        min: 72,
        max: 300,
        step: 25,
        unit: 'DPI',
      },
      {
        key: 'tools.pdf.autoOcr',
        category: 'tools',
        label: 'Auto-Recognize Scanned Text',
        description: 'Automatically extract readable text from scanned documents.',
        type: 'boolean',
        default: false,
      },
      {
        key: 'tools.pdf.compressionLevel',
        category: 'tools',
        label: 'Document File Size Optimization',
        description: 'Compression level when saving merged PDFs.',
        type: 'enum',
        default: 'medium',
        options: [
          { value: 'low', label: 'Fastest' },
          { value: 'medium', label: 'Balanced (Recommended)' },
          { value: 'high', label: 'Smallest File Size' },
        ],
      },
    ],
  },
  {
    suiteId: 'video',
    suiteName: 'Video Studio',
    icon: 'Video',
    settings: [
      {
        key: 'tools.video.crf',
        category: 'tools',
        label: 'Default Video Quality Level',
        description: 'Video compression balance (15–35, lower means higher quality).',
        type: 'number',
        default: 23,
        min: 15,
        max: 35,
        step: 1,
      },
      {
        key: 'tools.video.preset',
        category: 'tools',
        label: 'Export Speed vs Size',
        description: 'Speed and compression balance for video exports.',
        type: 'enum',
        default: 'medium',
        options: [
          { value: 'ultrafast', label: 'Ultra Fast' },
          { value: 'fast', label: 'Fast' },
          { value: 'medium', label: 'Balanced' },
          { value: 'slow', label: 'Smallest Size' },
        ],
      },
      {
        key: 'tools.video.twoPass',
        category: 'tools',
        label: 'High Precision Encoding',
        description: 'Perform an extra quality pass for best video clarity.',
        type: 'boolean',
        default: false,
      },
    ],
  },
  {
    suiteId: 'audio',
    suiteName: 'Audio Studio',
    icon: 'Music',
    settings: [
      {
        key: 'tools.audio.sampleRate',
        category: 'tools',
        label: 'Sound Quality Rate',
        description: 'Sound frequency rate for exports.',
        type: 'enum',
        default: 44100,
        options: [
          { value: 44100, label: '44.1 kHz (CD Quality)' },
          { value: 48000, label: '48.0 kHz (Studio Quality)' },
        ],
      },
      {
        key: 'tools.audio.noiseReduction',
        category: 'tools',
        label: 'Background Noise Removal',
        description: 'Automatically filter out background hums and room noise from voice recordings.',
        type: 'boolean',
        default: true,
      },
      {
        key: 'tools.audio.normalizeLoudness',
        category: 'tools',
        label: 'Equalize Volume Levels',
        description: 'Balance audio volume so tracks play at standard loudness.',
        type: 'boolean',
        default: true,
      },
    ],
  },
  {
    suiteId: 'text',
    suiteName: 'Text & Code Editor',
    icon: 'FileCode',
    settings: [
      {
        key: 'tools.text.diffMode',
        category: 'tools',
        label: 'Comparison View',
        description: 'Side-by-side split vs. single unified list.',
        type: 'enum',
        default: 'split',
        options: [
          { value: 'split', label: 'Side-by-Side Split' },
          { value: 'unified', label: 'Single Column' },
        ],
      },
      {
        key: 'tools.text.tabSize',
        category: 'tools',
        label: 'Tab Indentation Spaces',
        description: 'Number of spaces per tab indent.',
        type: 'number',
        default: 2,
        min: 2,
        max: 8,
        step: 2,
        unit: 'spaces',
      },
      {
        key: 'tools.text.wordWrap',
        category: 'tools',
        label: 'Wrap Long Lines',
        description: 'Wrap long lines of text to fit your screen.',
        type: 'boolean',
        default: true,
      },
    ],
  },
  {
    suiteId: 'archive',
    suiteName: 'Zip & Archive Tools',
    icon: 'Folder',
    settings: [
      {
        key: 'tools.archive.defaultFormat',
        category: 'tools',
        label: 'Default Archive Format',
        description: 'Format used when creating compressed zip folders.',
        type: 'enum',
        default: 'zip',
        options: [
          { value: 'zip', label: 'ZIP' },
          { value: 'tar', label: 'TAR' },
          { value: 'gz', label: 'GZ' },
        ],
      },
      {
        key: 'tools.archive.compressionLevel',
        category: 'tools',
        label: 'Compression Strength',
        description: 'Compression ratio (1–9).',
        type: 'number',
        default: 6,
        min: 1,
        max: 9,
        step: 1,
      },
    ],
  },
  {
    suiteId: 'qr',
    suiteName: 'QR Code Generator',
    icon: 'Activity',
    settings: [
      {
        key: 'tools.qr.errorCorrection',
        category: 'tools',
        label: 'Damage & Scrape Recovery',
        description: 'How well the QR code scans even if partly covered or smudged.',
        type: 'enum',
        default: 'M',
        options: [
          { value: 'L', label: 'Standard (7% recovery)' },
          { value: 'M', label: 'Medium (15% recovery)' },
          { value: 'Q', label: 'High (25% recovery)' },
          { value: 'H', label: 'Maximum (30% recovery)' },
        ],
      },
      {
        key: 'tools.qr.margin',
        category: 'tools',
        label: 'Border Margin',
        description: 'Padding space around the QR code.',
        type: 'number',
        default: 4,
        min: 1,
        max: 10,
        step: 1,
        unit: 'modules',
      },
    ],
  },
  {
    suiteId: 'spreadsheet',
    suiteName: 'Table & CSV Tools',
    icon: 'Database',
    settings: [
      {
        key: 'tools.spreadsheet.delimiter',
        category: 'tools',
        label: 'CSV Separator Character',
        description: 'Separator character used when reading CSV tables.',
        type: 'enum',
        default: ',',
        options: [
          { value: ',', label: 'Comma (,)' },
          { value: ';', label: 'Semicolon (;)' },
          { value: '\t', label: 'Tab' },
        ],
      },
      {
        key: 'tools.spreadsheet.autoParseDates',
        category: 'tools',
        label: 'Automatically Format Dates',
        description: 'Format timestamps into standard readable dates.',
        type: 'boolean',
        default: true,
      },
    ],
  },
  {
    suiteId: 'ebook',
    suiteName: 'E-book Tools',
    icon: 'Globe',
    settings: [
      {
        key: 'tools.ebook.format',
        category: 'tools',
        label: 'Default E-book Format',
        description: 'Format used when creating e-books.',
        type: 'enum',
        default: 'epub',
        options: [
          { value: 'epub', label: 'EPUB' },
          { value: 'mobi', label: 'MOBI' },
          { value: 'pdf', label: 'PDF' },
        ],
      },
      {
        key: 'tools.ebook.fontSize',
        category: 'tools',
        label: 'Default Reading Font Size',
        description: 'Standard text size in reader view.',
        type: 'number',
        default: 18,
        min: 12,
        max: 32,
        step: 1,
        unit: 'px',
      },
    ],
  },
  {
    suiteId: 'presentation',
    suiteName: 'Presentation Tools',
    icon: 'Palette',
    settings: [
      {
        key: 'tools.presentation.aspectRatio',
        category: 'tools',
        label: 'Slide Dimensions',
        description: 'Standard slide proportion.',
        type: 'enum',
        default: '16:9',
        options: [
          { value: '16:9', label: 'Widescreen (16:9)' },
          { value: '4:3', label: 'Standard (4:3)' },
        ],
      },
      {
        key: 'tools.presentation.transition',
        category: 'tools',
        label: 'Slide Transition Style',
        description: 'Visual animation when moving between slides.',
        type: 'enum',
        default: 'fade',
        options: [
          { value: 'fade', label: 'Fade' },
          { value: 'slide', label: 'Slide' },
          { value: 'none', label: 'Instant' },
        ],
      },
    ],
  },
  {
    suiteId: 'security',
    suiteName: 'Security & Hashes',
    icon: 'Shield',
    settings: [
      {
        key: 'tools.security.hashAlgorithm',
        category: 'tools',
        label: 'File Checksum Type',
        description: 'Algorithm used for verifying file integrity.',
        type: 'enum',
        default: 'SHA-256',
        options: [
          { value: 'SHA-256', label: 'SHA-256 (Recommended)' },
          { value: 'SHA-512', label: 'SHA-512 (High Security)' },
          { value: 'MD5', label: 'MD5 (Quick Checksum)' },
        ],
      },
      {
        key: 'tools.security.keyLength',
        category: 'tools',
        label: 'Encryption Key Strength',
        description: 'Bit length for file encryption.',
        type: 'enum',
        default: 256,
        options: [
          { value: 128, label: '128-bit' },
          { value: 256, label: '256-bit (Maximum Security)' },
        ],
      },
    ],
  },
];

export const DEFAULT_KEYBINDINGS: Record<string, { label: string; key: string }> = {
  'nav.home': { label: 'Open Home Hub', key: 'Alt + 1' },
  'nav.pixels': { label: 'Open Photo Studio', key: 'Alt + 2' },
  'nav.canvas': { label: 'Open Drawing Canvas', key: 'Alt + 3' },
  'nav.pdf': { label: 'Open PDF Studio', key: 'Alt + 4' },
  'nav.video': { label: 'Open Video Studio', key: 'Alt + 5' },
  'nav.audio': { label: 'Open Audio Studio', key: 'Alt + 6' },
  'nav.text': { label: 'Open Text Editor', key: 'Alt + 7' },
  'app.settings': { label: 'Open Settings', key: 'Alt + S' },
  'app.theme': { label: 'Toggle Light / Dark Theme', key: 'Alt + T' },
};
